config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost", :port => 3001
  devise_for :users, path: 'accounts'

  devise_scope :user do
    authenticated :user do
      root 'feeds#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end

    resources :stories, only: %i[new index show create]
  end

  resources :stories, only: :destroy

  resources :posts do
    resources :comments, shallow: true, except: %i[new index show]
    resources :likes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy update]

  get :search, to: 'main#search'
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  belongs_to :user
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy, inverse_of: :parent
  has_many :likes, as: :likeable, dependent: :destroy

  validates :body, presence: true, length: { maximum: 220 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[create]

  def create
    @comment = @post.comments.new(comment_params.merge(user: current_user))
    authorize comment
    respond_to do |format|
      if comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
      else
        format.html { redirect_to @post, notice: 'Comment was not created.'  }
      end
      format.turbo_stream
    end
  end

  def edit
    authorize comment
  end

  def update
    authorize comment
    respond_to do |format|
      if comment.update(comment_params)
        format.html { redirect_to comment_url(comment), notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
      format.turbo_stream
    end
  end

  def destroy
    authorize comment
    comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to comment.post, notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  def comment
    @comment ||= Comment.includes(:user).find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id, :parent_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  include ActionView::RecordIdentifier

  def dom_id_for_records(*records, prefix: nil)
    records.map do |record|
      dom_id(record, prefix)
    end.join('_')
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do%>
  <div class = "comment py-3 w-100">
    <div class= "d-flex justify-content-start comment-inner">
      <div>
        <%=render partial: 'shared/avatar', locals: {user: comment.user, size: 30}%>
      </div>
      <div class = "px-2 comment-info w-100">
        <p class="modal-title text-wrap">
         <strong><%= comment.user.username %></strong>
         <span>
          <%= comment.body %>
         </span>
        </p>
         <div class = "d-flex justify-content-between">
          <p class = "comment-date">
            <% updated_at = comment.updated_at%>
            <%= updated_at.strftime("%B #{updated_at.day.ordinalize}, %Y") %>
          </p>
          <p class = "comment-links">
            <%= render partial: "comments/conditional_edit_delete", locals: {comment: comment}%>
          </p>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/comments/_conditional_edit_delete.html.erb
<%if policy(comment).edit? %>
  <%= link_to 'Edit', edit_comment_path(comment), data:{turbo: true}%>
<%end%>
<%if policy(comment).destroy?%>
 <%= link_to 'Delete', comment_path(comment), data: {turbo: true, turbo_method: :delete, turbo_confirm: "Are you sure?"} ,class: "mr-2"%>
<%end%>

app/views/comments/_form.html.erb
<% model = [local_assigns[:post], comment].compact %>
<%= form_with(model: model, id: dom_id_for_records(*model), class: "comment-form", data: {turbo: true}) do |form| %>
  <%= render partial: 'shared/form_errors', locals: {record: comment}%>
  <div class = "d-flex">
    <div class="field w-100 h-100">
      <%= form.text_field :body,placeholder: "Add a comment...", class: "new-comment border-0 w-100 h-100"%>
    </div>
    <div class="actions">
      <%= form.submit 'Post',class: "simple-btn submit-comment"%>
    </div>
  </div>
  <%= link_to 'Cancel', comment, class: "btn btn-link" if form.object.persisted? %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%if @comment.persisted? %>
  <%= comment = Comment.new %>
  <%= turbo_stream.append "#{dom_id(@post)}_comments", @comment %>
  <%= turbo_stream.replace dom_id_for_records(@post, comment ), partial: "comments/form", locals: { comment: comment , post: @post} %>
<%else%>
 <%= turbo_stream.replace(dom_id_for_records(@post, @comment), partial: 'comments/form', locals: { comment: @comment, post: @post }) %>
<%end%>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment%>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do%>
  <%= render partial: 'comments/form', locals: {comment: @comment }%>
<%end%>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do%>
  <%= render @comment%>
<%end%>

app/views/comments/update.turbo_stream.erb
<%if @comment.valid? %>
  <%= turbo_stream.replace @comment%>
<%else%>
 <%= turbo_stream.replace(@comment, partial: 'comments/form', locals: { comment: @comment, post: @post }) %>
<%end%>