config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost", :port => 3001
  devise_for :users, path: 'accounts'

  devise_scope :user do
    authenticated :user do
      root 'feeds#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end

    resources :stories, only: %i[new index show create]
  end

  resources :stories, only: :destroy

  resources :posts do
    resources :comments, shallow: true, except: %i[new index show]
    resources :likes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy update]

  get :search, to: 'main#search'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    authorize @like
    respond_to do |format|
      if @like.save
        @likeable = @like.likeable
        format.js
      else
        format.html { redirect_back(fallback_location: @likeable) }
      end
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    authorize @like
    @likeable = @like.likeable
    @like.destroy
    respond_to do |format|
      format.js
      format.html { redirect_back(fallback_location: post_path) }
    end
  end

  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_date(likeable)
    like = likeable.user.likes.find_by(likeable: likeable)
    like&.updated_at&.strftime("%B #{like.updated_at.day.ordinalize}, %Y")
  end
end

app/views/likes/_button.html.erb
<% unless !user_signed_in? %>
  <% like = current_user.likes.find_by(likeable: likeable) %>
  <% if like.nil? %>
  <%=button_to(likes_path, class: "simple-btn", params:{ like: {likeable_id: likeable.id,  likeable_type: likeable.class.to_s}}) do%>
      <h4><i class="bi bi-suit-heart"></i></h4>
  <% end%>
  <% else %>
    <%=button_to(like_path(like), class: "simple-btn", method: :delete) do%>
      <h4><i style = "color: red;" class="bi bi-heart-fill"></i></h4>
    <%end%>
  <% end %>
<%end%>

app/views/likes/_form.html.erb
<div>
  <% like = current_user.likes.find_by(likeable: likeable)%>
    Likes: <%= likeable.likes.count %>
  <% if like.nil? %>
    <%= form_with(model: [likeable, likeable.likes.build] , remote: true) do |form| %>
      <input type="text" name="like[likeable_id]" value="<%= likeable.id %>" />
      <input type="text" name="like[likeable_type]" value="<%= likeable.class.to_s %>" />
      <div class="actions">
        <%= form.submit "Like"%>
      </div>
    <%end%>
  <%else%>
    <%= form_with(model: [likeable, likeable.likes.find_by(user_id: current_user.id)],method: :delete, remote: true) do |form| %>
      <div class="actions">
        <%= form.submit "Unlike"%>
      </div>
    <%end%>
  <%end%>
</div>

app/views/likes/_like.html.erb
<% unless !user_signed_in? %>
  <% like = current_user.likes.find_by(likeable: likeable) %>
  <% if like.nil? %>
  <%=button_to(post_likes_path(likeable), class: "simple-btn", remote: true ,params:{ like: {likeable_id: likeable.id,  likeable_type: likeable.class.to_s}}) do%>
    <div class = "like-button">
      <span class = "heart-icon"><i class="bi bi-suit-heart"></i></span>
      <p class = "text-sm">
        <%= pluralize(likeable.likes.count , "like") %>
      <p>
    </div>
  <% end%>
  <% else %>
    <%=button_to(post_like_path(likeable, like), class: "simple-btn",remote: true, method: :delete) do%>
    <div class = "like-button">
      <span class = "heart-icon"><i style = "color: red;" class="bi bi-heart-fill"></i></span>
      <p class = "text-sm">
      <%= pluralize(likeable.likes.count , "like") %>
    </div>
    <%end%>
  <% end %>
<%end%>

app/views/likes/_update_like.js.erb
var like_button = document.querySelector("#like-button-<%= @likeable.id %>")
var like_button_detail = document.querySelector("#like-button-detail-<%= @likeable.id %>")
if (like_button !== null)
{
  like_button.innerHTML = ("<%= j render partial: 'likes/like', locals: { like: @like, likeable: @likeable}  %>")
}
if (like_button_detail !== null)
{
  like_button_detail.innerHTML = ("<%= j render partial: 'likes/like', locals: { like: @like, likeable: @likeable}  %>")
}

app/views/likes/create.js.erb
<%=render partial: 'likes/update_like', locals: {like: @like, likeable: @likeable}%>

app/views/likes/destroy.js.erb
<%=render partial: 'likes/update_like', locals: {like: @like, likeable: @likeable}%>