config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost", :port => 3001
  devise_for :users, path: 'accounts'

  devise_scope :user do
    authenticated :user do
      root 'feeds#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end

    resources :stories, only: %i[new index show create]
  end

  resources :stories, only: :destroy

  resources :posts do
    resources :comments, shallow: true, except: %i[new index show]
    resources :likes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy update]

  get :search, to: 'main#search'
end

app/views/shared/_avatar.html.erb
<% if local_assigns.key?(:border) %>
  <% style = local_assigns[:border]%>
 <div class = "">
    <%= image_tag user_avatar(user, size), class: "rounded-circle #{style}" %>
  </div>
<%else%>
  <div class = "">
    <%= image_tag user_avatar(user, size), class: "rounded-circle" %>
  </div>
<%end%>

app/views/shared/_brand.html.erb
<%= image_tag 'https://i.imgur.com/wvLiKam.png', size: size , class:"navbar-brand" %>

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="post-carousel carousel slide w-100 h-100" data-bs-ride="carousel">
  <div class="carousel-inner w-100 h-100  d-flex align-items-center ">
    <div class="carousel-item active">
      <%= image_tag(images.first, class: "carousel-image img-fluid d-block w-100") %>
    </div>
    <% images.drop(1).each do |image| %>
      <div class="carousel-item">
        <%= image_tag(image, class: "carousel-image img-fluid d-block w-100") %>
      </div>
    <%end%>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_flash.html.erb
<div class = "py-5">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/shared/_follow_requests.html.erb
<div id="follow-request-<%=user.id%>" class="d-flex justify-content-between align-items-center py-2">
  <%= link_to user ,class: "nav-link text-bold" do%>
    <div class = "d-flex">
      <%=render partial: 'shared/avatar', locals: {user: user, size: 40}%>
      <div class = "d-flex justify-content-between align-items-center">
        <div class = "px-2">
          <p class="sidebar-title card-title">
            <%= user.username %>
          </p>
          <p class="card-subtitle sidebar-subtitle">Requested</p>
        </div>
      </div>
    </div>
  <%end%>
  <span class="sidebar-btn">
    <%= render 'users/accept_follow_request', user: user%>
  </span>
</div>

app/views/shared/_follow_requests_dropdown.html.erb
<%follow_request_count = user.follow_requests.count%>
<div class="dropdown follow-request-dropdown">
  <button class="position-relative border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <h4><i class="bi bi-suit-heart"></i></h4>
    <% if follow_request_count > 0%>
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= follow_request_count %>
      </span>
    <%end%>
  </button>
  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
      <li><h6 class="dropdown-header">Follow Requests</h6></li>
    <li>
      <%= render partial: "shared/follow_requests", collection: user.follow_requests, as: :user%>
    </li>
  </ul>
</div>

app/views/shared/_form_errors.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this <%= record.class.name %> from being saved:</h2>
    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_grid.html.erb
<div class="container-md py-5 grid">
  <div id = "posts_grid" class="row row-cols-3">
      <%= render partial: 'posts/list', collection: posts, as: :list %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav">
  <div class="container">
    <%= link_to authenticated_root_path do%>
        <%= render partial: 'shared/brand', locals: {size: '120x58'}%>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <div class="navbar-search d-flex justify-content-center">
          <%= render "main/search", class: "d-flex form-inline" %>
      </div>
      <%= render partial: "shared/navbar_partial"%>
    </div>
  </div>
</nav>

app/views/shared/_post.html.erb
<div id = "posts-feed-<%= post.id %>" class="card-wrapper flex-container mb-4">
  <div class="card-header grid">
    <div class="header-img-container flex-container">
          <%=render partial: 'shared/avatar', locals: {user: post.user, size: 40}%>
    </div>
    <p class="card-title">
      <%= post.user.username %>
    </p>
    <div class="card-opt-btn flex-container">
    <i class="bi bi-three-dots"></i>
    </div>
  </div>
  <div class="card-img-container d-flex justify-content-center">
    <%= image_tag(post.images.first, class: "img-fluid")%>
  </div>
  <div class="card-data flex-container">
    <div class="card-icons flex-container">
      <span  class="card-icon card-icon-left">
        <div id="like-button-<%= post.id %>">
          <%= render 'likes/like', likeable: post %>
        </div>
      </span>
      <span class="card-icon card-icon-left pb-4">
        <%= link_to post, data:{turbo: true, turbo_frame: "detail"} do%>
          <i class="bi bi-chat"></i>
        <%end%>
      </span>

      <span class="card-icon card-icon-right pb-4 d-flex justify-content-end">
          <%= render partial: 'posts/conditional_edit_delete', locals: {post: post}%>
      </span>
    </div>
    <span class="card-text">
      <span class="bold title-margin">
      <%= post.user.username %>
      </span>
      <%=post.body%>
    </span>
    <div class="card-time text-muted">
     <%= date(post) %>
    </div>

    <span class="card-text comments-btn">
      <%= link_to "See more comments",post, data:{turbo: true, turbo_frame: "detail"} %>
    </span>

    <div class = "w-100 ">
      <%= tag.div id: "#{dom_id(post)}_comments" ,class: "card-comments" do %>
        <%= render post.comments %>
      <%end%>
    </div>
    <div class="add-comment-container flex-container">
      <span class="card-icon"><i class="bi bi-emoji-smile"></i></span>
      <div class="comment-container">
        <%= render partial: 'comments/form', locals: {parent_id: nil, post: post, comment: Comment.new} %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stories.html.erb
<div class="d-flex justify-content-start align-items-center border mb-4 py-4 px-2 rounded-2 stories-container">
  <div class=  "text-center d-flex align-items-center">
    <%= link_to new_story_path, data:{turbo: true, turbo_frame: "modal"}, class:"display-2 px-2" do %>
      <i class="bi bi-plus-circle"></i>
    <%end%>
  </div>
  <%= render partial: "shared/story", collection: User.with_story, as: :user%>
</div>

app/views/shared/_suggestion.html.erb
<div class="d-flex justify-content-between align-items-center py-2">
  <%= render partial: "shared/user_info", locals: {user: user, subtitle: "Suggested for you"}%>
  <span class="sidebar-btn">
    <%= link_to user_path(user) do %>
      Show
    <%end%>
  </span>
</div>

app/views/shared/_user_info.html.erb
<div class= "user-info">
  <%= link_to user_path(user) do %>
    <div class = "d-flex ">
      <%=render partial: 'shared/avatar', locals: {user: user, size: 40}%>
      <div class = "d-flex justify-content-between align-items-center">
        <div class = "px-2">
          <p class="user-info-title">
            <%= user.username %>
          </p>
          <p class="user-info-subtitle"><%=subtitle%></p>
        </div>
      </div>
    </div>
  <%end%>
</div>