config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost", :port => 3001
  devise_for :users, path: 'accounts'

  devise_scope :user do
    authenticated :user do
      root 'feeds#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end

    resources :stories, only: %i[new index show create]
  end

  resources :stories, only: :destroy

  resources :posts do
    resources :comments, shallow: true, except: %i[new index show]
    resources :likes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy update]

  get :search, to: 'main#search'
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :attachment

  validates :body, presence: true, length: { maximum: 2200 }
  validates :attachment, attached: true

  after_create_commit -> {
    StoriesCleanupJob.set(wait: 24.hours).perform_later(id)
  }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_user, only: :index

  def index
    @stories = @user.stories.all
    respond_to do |format|
      format.html
      format.json do
        render json: @stories
      end
    end
  end

  def show
    render json: story
  end


  def new
    @story = current_user.stories.new
    authorize story
  end

  def create
    @story = current_user.stories.new(story_params)
    authorize story
    if story.save
      redirect_to authenticated_root_path, notice: 'Story was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize story
    story.destroy
    redirect_back fallback_location: authenticated_root_path, notice: 'Story was successfully destroyed.'
  end

  private

  def story
    @story ||= Story.find(params[:id])
  end

  def set_user
    @user = User.find_by!(username: params[:user_id])

    rescue ActiveRecord::RecordNotFound
      render  json: { error: "resource not found" }, status: :not_found
  end

  def story_params
    params.require(:story).permit(:body, :attachment)
  end
end

app/views/stories/_form.html.erb
<%= form_with(model: [current_user, story],local: true, class:"w-100 h-100") do |form| %>
  <%= render partial: "shared/form_errors", locals: {record: story}%>

  <div class = "w-100 h-100" data-controller = "image-preview">
    <div class = "post-image-preview p-5"  style = "height: 80%">
      <div id="carouselExampleControls" class="carousel slide w-100 h-100" data-bs-ride="carousel" style = "height: 400px;">
        <div class="carousel-inner w-100 h-100" data-image-preview-target = "output"></div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
      </div>
    </div>

    <%= form.file_field :attachment, id: "files", class:"form-control", required: true, data: {image_preview_target: "input", action: "input->image-preview#readURL" }%>
    <div class="field">

      <%= form.text_field :body ,data: {action: "input->image-preview#Test" },class: "form-control", placeholder: "Write something"%>
    </div>

    <div class="actions">
      <%= form.submit "Post", class:"btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/stories/_stories_list.html.erb
<div class="d-flex justify-content-start align-items-center border mb-4 py-4 px-2 rounded-2 stories-container">
  <div class=  "text-center d-flex align-items-center">
    <%= link_to new_user_story_path(current_user), data:{turbo: true, turbo_frame: "modal"}, class:"display-2 px-2" do %>
      <i class="bi bi-plus-circle"></i>
    <%end%>
  </div>
  <%= render partial: "stories/story_noti", collection: users, as: :user%>
</div>

app/views/stories/_story.html.erb
<div class = "story w-100 h-100 d-flex justify-content-center align-items-center">
  <div class = "story-inner h-100 d-flex align-items-center">
    <div>
      <%if policy(story).destroy? %>
        <%= link_to 'Delete Story',story_path(story), method: :delete%>
      <%end%>
      <% if story.attachment.present? %>
        <% if story.attachment.image? %>
          <%= image_tag(story.attachment,class: "img-fluid d-block w-100 rounded-3", style: "max-height:800px") %>
        <%else%>
          <%= video_tag url_for(story.attachment), controls: true, class: "rounded-3" %>
        <%end%>
      <%else%>
        <div>
          <p>Attachment isn't available</p>
        </div>
      <%end%>
    </div>
    <% if !story.body.nil? %>
      <div class = "story-body">
        <%= story.body %>
      </div>
    <%end%>
  </div>
</div>

app/views/stories/_story_noti.html.erb
<span class="px-2 d-flex align-items-center story-container">
  <div class="justify-content-center align-items-center text-center ">
     <%= link_to user_stories_path(user), data: {turbo: "true", turbo_frame: "story_detail"} do  %>
      <%=render partial: 'shared/avatar', locals: {user: user, size: 60, border: "border border-info border-3"}%>
      <p><%= user.username %></p>
    <%end%>
  </div>
</span>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<%= turbo_frame_tag "story_detail"  do%>
  <%= tag.div data: { controller: "story-view"}, class: "" do %>
    <div class="modal fade" id="story-detail-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
         <div class="modal-header">
          <h5 class="modal-title"> Stories for  <%=@user.username%> </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
          <div class="modal-body">
            <div id="carouselExampleControls" class="carousel slide w-50 h-100 d-flex justify-content-center align-items-center" data-bs-ride="true">
              <div class="carousel-inner  rounded-4 h-100">
                <%if @stories.any?%>
                  <div class="carousel-item active w-100 h-100">
                    <%=render partial: 'stories/story', locals: {story: @stories.first} %>
                  </div>
                  <% @stories.drop(1).each do |story| %>
                    <div class="carousel-item w-100 h-100">
                      <%=render partial: 'stories/story', locals: {story: story} %>
                    </div>
                  <%end%>
                <%else%>
                 <div class="carousel-item active w-100 h-100">
                    <div class =  "h-100 w-100 text-center"><h6 style= "color: white">This story isnt available anymore</h6></div>
                  </div>
                <%end%>
                </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>

          </div>
        </div>
      </div>
    </div>
  <%end%>
<%end%>

app/views/stories/new.html.erb
<%= render TurboModalComponent.new(title: "Create new story") do%>
  <%= render 'form', story: @story %>
<%end%>